POST http://localhost:8080/store/order
Content-Type: application/json

{
  "token": 7323243919010337254,
  "order": {
    "id": 0,
    "petId": 0,
    "quantity": 0,
    "shipDate": "2020-02-20T10:13:50.094Z",
    "status": "placed",
    "complete": true
  }
}

###

GET http://localhost:8080/store/order/0
Content-Type: application/json

{
  "token": 7323243919010337254
}

###

DELETE http://localhost:8080/store/order/0
Content-Type: application/json

{
  "token": 7323243919010337254
}

###

GET http://localhost:8080/store/inventory
Content-Type: application/json

{
  "token": 7323243919010337254,
  "petStatus": "available"
}

###