GET http://localhost:8080/user/0
Content-Type: application/json

{
  "token": -7216449629386979394
}

###

PUT http://localhost:8080/user/0
Content-Type: application/json

{
  "token": 7323243919010337254,
  "user": {
    "id": 0,
    "userName": "string",
    "firstName": "test",
    "lastName": "superTest",
    "email": "test",
    "password": "test",
    "phone": "test",
    "userStatus": 0
  }
}

###

DELETE http://localhost:8080/user/0
Content-Type: application/json

{
  "token": 7323243919010337254
}

###

POST http://localhost:8080/user/login
Content-Type: application/json

{
  "user": {
    "id": 0,
    "login": "string",
    "password": "string"
  }
}

###

POST http://localhost:8080/user/logout
Content-Type: application/json

{
  "token": 7323243919010337254
}

###

POST http://localhost:8080/user
Content-Type: application/json

{
  "id": 0,
  "userName": "string",
  "firstName": "string",
  "lastName": "string",
  "email": "string",
  "login": "string",
  "password": "string",
  "phone": "string",
  "userStatus": 0,
  "token": null
}

###
