GET http://localhost:8080/user/1
Content-Type: application/json

{
  "token": "498163928"
}

###

PUT http://localhost:8080/user/1
Content-Type: application/json

{
  "token": "498163928",
  "user": {
    "id": 1,
    "userName": "Test-string",
    "firstName": "Test-string",
    "lastName": "Test-string",
    "email": "Test-string",
    "login": "Test-string",
    "password": "string",
    "phone": "string",
    "userStatus": 0,
    "token": "498163928"
  }
}

###

DELETE http://localhost:8080/user/1
Content-Type: application/json

{
  "token": "498163928"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json

{
  "user": {
    "id": 1,
    "login": "string",
    "password": "string"
  }
}

###

POST http://localhost:8080/user/logout
Content-Type: application/json

{
  "token": "498163928"
}

###

POST http://localhost:8080/user
Content-Type: application/json

{
  "id": 3,
  "userName": "string",
  "firstName": "string",
  "lastName": "string",
  "email": "string",
  "login": "string",
  "password": "string",
  "phone": "string",
  "userStatus": 0,
  "token": null
}

###
